REMOVE="
/system/fonts/DroidSansMono.ttf
/system/fonts/CutiveMono.ttf
/system/fonts/NotoSansCJK-Regular.ttc
/system/fonts/NotoSerifCJK-Regular.ttc
/system/fonts/NotoSerif-Regular.ttf
/system/fonts/NotoSerif-Bold.ttf
/system/fonts/NotoSerif-Italic.ttf
/system/fonts/NotoSerif-BoldItalic.ttf
/system/product/fonts
/system/product/etc/fonts_customization.xml
"
